contact_links:
  - name: "\U0001F914 If you have a question or an issue about one of the tools in Jupyter,
    we recommend asking in the Jupyter community Discourse forum."
    url: https://discourse.jupyter.org
    about: This repository is the home of the Jupyter-wide documentation. However,
           it **not** the best place to ask questions about Jupyter.